services:
  eureka-server:
    build: ./eureka-server    # Changed from ./ewallet-services/eureka-server
    ports:
      - "8761:8761"

  user-service:
    build: ./user-services    # Changed from ./ewallet-services/user-services
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/userDb
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - mysql-db
      - eureka-server

  # Use the images you already have in your screenshot
  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  my-local-redis:
    image: redis
    ports:
      - "6379:6379"

  kafka:
    image: apache/kafka:latest
    ports:
      - "9092:9092"