spring:
  application:
    name: user-service # This tells the Config Server which file to grab
  config:
    # Use the Docker container name!
    import: optional:configserver:http://config-server:8888